# Generated by Django 2.0.4 on 2018-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionsEvaluations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=0, max_length=2048, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'チャンピオン評価トラン',
                'db_table': 't_champions_evaluations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
